### ISSUE TITLE
Great Idea

### ISSUE THREAD

**Issue by Professor-Paradox** [Da-Viper/kde_theme_script#1]
I had the same idea of theme,switching then found your youtube channel a month ago helped me a lot to create my own implementation of it.
with bash.
now iam trying to extend it to have a better Ui,with python,
Great work on the scripts.
Do you know any KDE way to get all the installed themes,cursors,icons, from terminal.instead of their installation locations?,If do please respond my work was stuck on this point.

I can work with the file names but doing it with some KDE built command to just use and switch themes,would be great,without editing files.

**Comment by da-viper** [comment]
I'm sorry I do not understand your question could you be more elaborate on what you mean ? 


But if you want a gui there is this [this](https://github.com/baduhai/Koi) koi 

It's a theme switcher and it's very good

**Comment by Professor-Paradox** [comment]
**Question:**
1. Is their a way of getting the installed themes,icons, other options with some python commands?
2. Is their any other way to set/change themes,icons,windows,color schemes etc., than with kdeglobals,and other related files?

**Congrats**
Appreciating your work, it helped with my work,doing the same.

**Comment by da-viper** [comment]
you can use the global theme and write to it it can change all parts of plasma except gtk and kvantum styles 
sorry for the late response 
did not check notification
